<!-- Search -->
<div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-6 col-md-push-3 text-center pd-30">
    <div class="input-group text-center" style="width: 100%; min-width: 250px; max-width: 90%; left: 5%">
        <input id="search" type="search" class="form-control" placeholder="Tìm kiếm sản phẩm" style="border-radius: 30px 0px 0px 30px; border-right: unset; padding-left: 20px; height: 40px; font-size: 14px">
        <span id="icon-search" class="input-group-addon">
            <i class="fa fa-search"></i>
        </span>
    </div>
</div>

<!-- Swiper -->
<div class="banner-swiper-container swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'banner.png';?>" width="100%">
        </div>
        <div class="swiper-slide">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'banner.png';?>" width="100%">
        </div>
    </div>
    <!-- Add Pagination -->
    <div class="banner-swiper-pagination swiper-pagination" style="position: relative; bottom: 0"></div>
</div>

<!-- Menu icon -->
<div class="container" style="margin-top: 20px; margin-bottom: 10px">
    <div class="swiper-container menu-categories-icon">
        <div class="swiper-wrapper">
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'laptop.png';?>" width="100%">
                            <p>Máy tính / Laptop</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'nha.png';?>" width="100%">
                            <p>Nhà cửa / Đời sống</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'giadung.png';?>" width="100%">
                            <p>Thiết bị điện tử</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'bong.png';?>" width="100%">
                            <p>Thế thao / Du lịch</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'quanao.png';?>" width="100%">
                            <p>Thời trang</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'xe.png';?>" width="100%">
                            <p>Ôtô / Xe máy</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'phone.png';?>" width="100%">
                            <p>Điện thoại / Phụ kiện</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'son.png';?>" width="100%">
                            <p>Sức khỏa và sắc đẹp</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'laptop.png';?>" width="100%">
                            <p>Máy tính / Laptop</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'nha.png';?>" width="100%">
                            <p>Nhà cửa / Đời sống</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'giadung.png';?>" width="100%">
                            <p>Thiết bị điện tử</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'bong.png';?>" width="100%">
                            <p>Thế thao / Du lịch</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'quanao.png';?>" width="100%">
                            <p>Thời trang</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'xe.png';?>" width="100%">
                            <p>Ôtô / Xe máy</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="swiper-slide menu-categories-swiper-slide">
                <div class="list-2-categories">
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'phone.png';?>" width="100%">
                            <p>Điện thoại / Phụ kiện</p>
                        </a>
                    </div>
                    <div style="height: 5px; background: #d1d1d1"></div>
                    <div class="icon-category">
                        <a>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'son.png';?>" width="100%">
                            <p>Sức khỏa và sắc đẹp</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Top sản phẩm -->
<section class="container" style="margin-top: 20px; margin-bottom: 20px">
    <h4>
        Top sản phẩm &nbsp &nbsp
        <small>
            <a>Xem tất cả</a>
        </small>
    </h4>
    <div class="swiper-container product-swiper-container" id="product-swiper-container">
        <div class="swiper-wrapper">
            <?php
            $productList = $this->getSharedProductCollection();
                //$productModel = Mage::getSingleton('catalog/product');
            $_imgSize = 300;
            $currentVendorProfileId = Mage::registry('current_vendor')->getProfileId();
                //echo $list->getSize();
            ?>
            <?php foreach($productList as $productObj):?>
                <?php
                $images = $this->helper('catalog/image')->init($productObj, 'image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSize, null);
                $strCompare = strcmp($productObj->getProfileId(), $currentVendorProfileId);
                ?>
                <div class="swiper-slide product-swiper-slide">
                    <div class="product">
                        <div class="product-info">
                            <div class="product-img">
                                <img src="<?php echo $images;?>">
                            </div>
                            <div class="product-title mg-top-5">
                                <span class="name"><?php echo $productObj->getName();?></span>
                            </div>
                            <div class="price-product">
                                <span class="text-left">Giá bán</span>
                                <span class="pull-right"><?php echo $productObj->getSharedPrice();?> đ</span>
                                <div class="clearfix"></div>
                                <span class="text-left">Hoa hồng</span>
                                <span class="text-danger pull-right">0 đ</span>
                            </div>
                        </div>
                        <button class="btn button-vionli width-full btn-nhan-ban">
                            <small class="visible-xs">Nhận bán</small>
                            <span class="hidden-xs">Nhận bán</span>
                        </button>
                        <div class="clearfix"></div>
                        <div class="height-button-tmp">
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
        <!-- Add Arrows -->
        <div class="product-next swiper-button-next"></div>
        <div class="product-prev swiper-button-prev"></div>
    </div>
</section>

<!-- Sản phẩm mới nhất -->
<section class="container" style="margin-top: 20px; margin-bottom: 20px">
    <h4>
        Sản phẩm mới nhất &nbsp &nbsp
        <small>
            <a>Xem tất cả</a>
        </small>
    </h4>
    <div class="swiper-container best-product-swiper-container" id="best-product-swiper-container">
        <div class="swiper-wrapper">
            <?php
            $productList = $this->getSharedProductCollection();
                //$productModel = Mage::getSingleton('catalog/product');
            $_imgSize = 300;
            $currentVendorProfileId = Mage::registry('current_vendor')->getProfileId();
                //echo $list->getSize();
            ?>
            <?php foreach($productList as $productObj):?>
                <?php
                $images = $this->helper('catalog/image')->init($productObj, 'image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSize, null);
                $strCompare = strcmp($productObj->getProfileId(), $currentVendorProfileId);
                ?>
                <div class="swiper-slide best-product-swiper-slide">
                    <div class="product">
                        <div class="product-info">
                            <div class="product-img">
                                <img src="<?php echo $images;?>">
                            </div>
                            <div class="product-title mg-top-5">
                                <span class="name"><?php echo $productObj->getName();?></span>
                            </div>
                            <div class="price-product">
                                <span class="text-left">Giá bán</span>
                                <span class="pull-right"><?php echo $productObj->getSharedPrice();?> đ</span>
                                <div class="clearfix"></div>
                                <span class="text-left">Hoa hồng</span>
                                <span class="text-danger pull-right">0 đ</span>
                            </div>
                        </div>
                        <button class="btn button-vionli width-full btn-nhan-ban">
                            <small class="visible-xs">Nhận bán</small>
                            <span class="hidden-xs">Nhận bán</span>
                        </button>
                        <div class="clearfix"></div>
                        <div class="height-button-tmp">
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
        <!-- Add Arrows -->
        <div class="best-product-next swiper-button-next"></div>
        <div class="best-product-prev swiper-button-prev"></div>
    </div>
</section>

<div class="col-xs-12 col-md-4 col-md-push-4 text-center">
    <button class="btn btn-default btn-lg width-full" style="min-width: 250px; max-width: 300px; border-radius: 30px">Xem thêm sản phẩm</button>
</div>

<div class="clearfix"></div>

<!-- Sản phẩm đã xem -->
<section class="container" style="margin-top: 20px; margin-bottom: 20px">
    <h4>
        Sản phẩm đã xem &nbsp &nbsp
        <small>
            <a>Xem tất cả</a>
        </small>
    </h4>
    <div class="swiper-container seen-product-swiper-container" id="seen-product-swiper-container">
        <div class="swiper-wrapper">
            <?php
            $productList = $this->getSharedProductCollection();
                //$productModel = Mage::getSingleton('catalog/product');
            $_imgSize = 300;
            $currentVendorProfileId = Mage::registry('current_vendor')->getProfileId();
                //echo $list->getSize();
            ?>
            <?php foreach($productList as $productObj):?>
                <?php
                $images = $this->helper('catalog/image')->init($productObj, 'image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSize, null);
                $strCompare = strcmp($productObj->getProfileId(), $currentVendorProfileId);
                ?>
                <div class="swiper-slide seen-product-swiper-slide">
                    <div class="pd-15 product">
                        <div class="product-info">
                            <div class="product-img">
                                <img src="<?php echo $images;?>">
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
        <!-- Add Arrows -->
        <div class="seen-product-next swiper-button-next"></div>
        <div class="seen-product-prev swiper-button-prev"></div>
    </div>
</section>
<script type="text/javascript">
    var menuSlidesPerView = {
        mobile: 3,
        'mobile-hor': 4,
        tablet: 5,
        'tablet-lg': 7,
        desktop: 8,
        'desktop-lg': 10
    };

    var productSlidesPerView = {
        mobile: 2,
        'mobile-hor': 3,
        tablet: 3,
        'tablet-lg': 4,
        desktop: 6,
        'desktop-lg': 8
    }

    var device = '';

    function initSwiper() {
        if (window.innerWidth < 480) {
            device = 'mobile';
        } else if (window.innerWidth < 768 ) {
            device = 'mobile-hor';
        } else if (window.innerWidth < 1024) {
            device = 'tablet';
        } else if (window.innerWidth < 1025) {
            device = 'tablet-lg';
        } else if (window.innerWidth < 1440) {
            device = 'desktop';
        } else {
            device = 'desktop-lg';
        }
        console.log(device);
        var swiperBanner = new Swiper('.banner-swiper-container', {
            pagination: {
                el: '.banner-swiper-pagination',
                clickable: true
            },
            autoplay: {
                delay: 5000,
            },

        });
        var swiperMenu = new Swiper('.menu-categories-icon', {
            slidesPerView: menuSlidesPerView[device],
            spaceBetween: 3
        });
        var swiperProduct = new Swiper('.product-swiper-container', {
            slidesPerView: productSlidesPerView[device],
            spaceBetween: 0,
            navigation: {
                nextEl: '.product-next',
                prevEl: '.product-prev',
            }
        });
        var bestProduct = new Swiper('.best-product-swiper-container', {
            slidesPerView: productSlidesPerView[device],
            spaceBetween: 0,
            navigation: {
                nextEl: '.best-product-next',
                prevEl: '.best-product-prev',
            }
        });
        var seenProduct = new Swiper('.seen-product-swiper-container', {
            slidesPerView: productSlidesPerView[device],
            spaceBetween: 2,
            navigation: {
                nextEl: '.seen-product-next',
                prevEl: '.seen-product-prev',
            }
        });     
    }

    initSwiper();

    var supportsOrientationChange = "onorientationchange" in window,
        orientationEvent = supportsOrientationChange ? "orientationchange" : "resize";

    window.addEventListener("resize", function() {
        setTimeout(initSwiper, 500);
    }, false);

    jQuery(".input-group > input").focus(function(e){
        jQuery(this).parent().addClass("input-group-focus");
    }).blur(function(e){
        jQuery(this).parent().removeClass("input-group-focus");
    });
    jQuery( document ).ready(function() {
        jQuery(".swiper-button-next").css("background-image","url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'next.png';?>'");
        jQuery(".swiper-button-prev").css("background-image","url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'prev.png';?>'");
    });
</script>