<div class="col-xs-12 col-md-4 col-md-push-4 text-center pd-10">
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Tìm kiếm sản phẩm">
        <span class="input-group-addon">
                <i class="fa fa-search"></i>
            </span>
    </div>
</div>
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'banner.png';?>" width="100%">
        </div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
</div>
<div class="container" style="margin-top: 10px; margin-bottom: 10px">
    <div class="swiper-container menu-2-swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'laptop.png';?>" width="100%">
                    <h5>Máy tính / Laptop</h5>
                </div>
            </div>
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'giadung.png';?>" width="100%">
                    <h5>Thiết bị điện tử</h5>
                </div>
            </div>
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'son.png';?>" width="100%">
                    <h5>Sức khỏe và sắc đẹp</h5>
                </div>
            </div>
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'bong.png';?>" width="100%">
                    <h5>Thể thao và du lịch</h5>
                </div>
            </div>
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'phone.png';?>" width="100%">
                    <h5>Điện thoại và phụ kiện</h5>
                </div>
            </div>
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'nha.png';?>" width="100%">
                    <h5>Nhà cửa và đời sống</h5>
                </div>
            </div>
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'xe.png';?>" width="100%">
                    <h5>Ôtô và xe máy</h5>
                </div>
            </div>
            <div class="swiper-slide menu-2-swiper-slide">
                <div class="menu-2-img-1">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'vionli'.DS.'icon'.DS.'quanao.png';?>" width="100%">
                    <h5>Thời trang</h5>
                </div>
            </div>
        </div>
        <!-- Add Arrows -->
        <!-- <div class="swiper-button-next"></div> -->
        <!-- <div class="swiper-button-prev"></div> -->
    </div>
</div>
<section class="col-xs-12">
    <h4>
        Top sản phẩm
        <small>
            <a>Xem tất cả</a>
        </small>
    </h4>
    <div class="swiper-container product-swiper-container">
        <div class="swiper-wrapper">
            <?php
                $productList = $this->getSharedProductCollection();
                //$productModel = Mage::getSingleton('catalog/product');
                $_imgSize = 300;
                $currentVendorProfileId = Mage::registry('current_vendor')->getProfileId();
                //echo $list->getSize();
            ?>
            <?php foreach($productList as $productObj):?>
                <?php
                    $images = $this->helper('catalog/image')->init($productObj, 'image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSize, null);
                    $strCompare = strcmp($productObj->getProfileId(), $currentVendorProfileId);
                ?>
                <div class="swiper-slide product-swiper-slide">
                    <div class="pd-5 product-noborber">
                        <div class="product-info">
                            <div class="product-img">
                                <img src="<?php echo $images;?>">
                            </div>
                            <div class="title-product mg-top-5">
                                <span class="name"><?php echo $productObj->getName();?></span>
                            </div>
                            <div class="price-product">
                                <span class="text-left">Giá bán</span>
                                <span class="pull-right"><?php echo $productObj->getSharedPrice();?></span>
                                <div class="clearfix"></div>
                                <span class="text-left">Hoa hồng</span>
                                <span class="text-danger pull-right">0 đ</span>
                            </div>
                        </div>
                        <button class="btn button-vionli width-full" data-toggle="modal" data-target="#modal-product-receive">
                            <small class="visible-xs">Nhận bán</small>
                            <span class="hidden-xs">Nhận bán</span>
                        </button>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
    </div>
</section>



<!--<script type="text/javascript" src="Swiper/dist/js/swiper.min.js"></script>-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

<script type="text/javascript">
    var menuSlidesPerView = {
        mobile: 3,
        tablet: 5,
        'tablet-lg': 7,
        desktop: 8,
        'desktop-lg': 10
    };

    var productSlidesPerView = {
        mobile: 1,
        tablet: 3,
        'tablet-lg': 4,
        desktop: 6,
        'desktop-lg': 8
    }

    var device = '';

    if (window.innerWidth <= 480) {
        device = 'mobile';
    } else if (window.innerWidth <= 768) {
        device = 'tablet';
    } else if (window.innerWidth <= 1024) {
        device = 'tablet-lg';
    } else if (window.innerWidth < 1440) {
        device = 'desktop';
    } else {
        device = 'desktop-lg';
    }

    var swiper = new Swiper('.swiper-container', {
        pagination: {
            el: '.swiper-pagination',
        },
    });
    var swiperMenu = new Swiper('.menu-2-swiper-container', {
        slidesPerView: menuSlidesPerView[device],
        spaceBetween: 0,
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });
    var swiperProduct = new Swiper('.product-swiper-container', {
        slidesPerView: productSlidesPerView[device],
        spaceBetween: 0,
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });
</script>


































<?php return;?>

<!-- <script src='<?php //echo $this->getSkinUrl('js/jquery-3.1.0.js', array('_secure'=>true));?>' type='text/javascript'></script>
<script src='<?php //echo $this->getSkinUrl('js/bootstrap.js', array('_secure'=>true));?>' type='text/javascript'></script>-->
<!-- Vionli_Pubproduct_Block_Vendor_Admin_Product  -->
<?php 
    $productList = $this->getSharedProductCollection();
    //$productModel = Mage::getSingleton('catalog/product');
    $_imgSize = 300;
    $currentVendorProfileId = Mage::registry('current_vendor')->getProfileId();
    //echo $list->getSize();
?>
<div id="v_pub_product_list" class="got-sell-prod-item-wapper">
<?php //foreach($productList->getData() as $productData):?>
<?php foreach($productList as $productObj):?>
    <?php //Zend_Debug::dump($productObj->getData());?>
        <?php
        //$prod = $productModel->setId($productData['entity_id']);
            $images = $this->helper('catalog/image')->init($productObj, 'image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSize, null);
            $strCompare = strcmp($productObj->getProfileId(), $currentVendorProfileId);
            ?>
        <div class="col-md-3 col-sm-6 col-md-2 pd-5 prod-item-wapper vionli-product-item-area" data-pid="<?php echo $productObj->getId();?>">
            <div class="pd-5 product">
                <!--<img src="<?php /*echo $this->helper('catalog/image')->init($prod, 'image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSize, null); */?>" alt=""/>-->
                <div class="images-product" style="background-image: url('<?php echo $images; ?>');">
                </div>
                <div class="title-product mg-top-5">
                    <span class="name"><?php echo $productObj->getName();?></span>
                </div>
                <!--<p class="price"><?php /*echo $prod->getFinalPrice();*/?></p>-->
                <div class="price-product">
                    <span class="text-left">Giá bán</span>
                    <span class="pull-right"><?php echo $productObj->getSharedPrice();?></span>
                    <div class="clearfix"></div>
                    <span class="text-left hidden shared-price-title" >Hoa hồng</span>
                    <span class="text-danger pull-right shared-price-value hidden"></span>
                </div>
                <!--<button class="btn btn-success width-full">
                    <small class="visible-xs">Chia sẻ sản phẩm</small>
                    <span class="hidden-xs">Chia sẻ sản phẩm</span>
                </button>-->
                <?php if($productObj->getQty() > 0 && empty($productObj->getGotIt()) && $strCompare != 0):?> <!-- $productObj->getGotIt() cho biet san pham da nhan ban hay chua-->
                    <div class="got-sell-button">
                        <button type="button" class="bt btn btn-success width-full got-product-sell" id="" data-pid="<?php echo $productObj->getId();?>" value="Got Sell">Nhan Ban</button>
                    </div>
                <?php elseif(!empty($productObj->getGotIt())):?>
                    <div class="un-got-sell-button">
                        <button type="button" class="bt btn btn-success width-full un-got-product-sell" id="" data-pid="<?php echo $productObj->getId();?>" value="Got Sell">Huy nhan Ban</button>
                    </div>
                <?php elseif((int)0 === $strCompare):?>
                    <span>san pham cua ban</span>
                <?php else:?>
                    <span>Het hang</span>
                <?php endif;?>


            </div>
        </div>
<?php endforeach;?>
<!--<div>
    <h1>day la khu vuc hien thi noi dung chinh</h1>
    <ul>
        <li>Check qty, neu san pham do con it hang hoac het hang</li>
        <li>can lay thong tin gi them nua khong</li>
        <ul>
            <li>viet js plugin cho vu nhan ban, toi nay bat dau lam</li>
            <li>hoan thanh trong 2 ngay</li>
            <li>test hien thi them san pham nhan ban o vendor dashboard</li>
            <li>luu ý cache sau khi vendor them product, dam bao no work [hien thi trong vendor admin dashboard]</li>
            <li>chinh sua lai bottom area thanh version moi</li>

        </ul>
    </ul>
</div>-->
</div>
<script type="text/javascript">
    vj(document).ready(function(){
        "use strict";
        vj('#v_pub_product_list').vionliGotSellProduct({
            'url': {
                'url_gotsold_action': "<?php echo $this->getVendorUrlObj()->getUrl('shareandsold/ajax/gettingsold');?>",
                'url_ungotsold_action': "<?php echo $this->getVendorUrlObj()->getUrl('shareandsold/ajax/ungotsold');?>",
            },
            'button': {
                'class': {
                    'shareButton': 'got-product-sell',
                    'unShareButton': 'un-got-product-sell'
                },
                'text':{
                    'gotSellButtonText':'<?php echo $this->__("Nhan Ban");?>',
                    'unGotSellButtonText': '<?php echo $this->__("Huy Nhan Ban");?>'

                },
                'gotSellProduct': ':button.got-product-sell',
                'unGotSellProduct': ':button.un-got-product-sell'
            },
            'formKey': "<?php echo Mage::getSingleton('core/session')->getFormKey();?>",
            'elem' : 'div.got-sell-prod-item-wapper',
            'shared': {
                'sharedPriceTitle': ':span.shared-price-title',
                'sharedPriceValue': ':span.shared-price-value'
            },
        });
    });
</script>